### ISSUE TITLE
Figma design

### ISSUE THREAD

**Issue by vairiskovels** [askolds11/DatZ4019GroupProject#9]

**Comment by vairiskovels** [comment]
https://www.figma.com/file/egwKDheIjraoZ23aV3VMdK/OOP-projekts-team-library?type=design&node-id=0%3A1&mode=design&t=VNE61t8OiLNhNsXE-1

**Comment by vairiskovels** [comment]
Resolution: 1080x2220px

**Comment by askolds11** [comment]
https://material-foundation.github.io/material-theme-builder/
